# Site settings
title: DevMark Agency
description: Modern digital solutions for growing brands.
url: "https://marketing-page.vercel.app" # Typo fixed!
author: David Velez

# This tells Jekyll where to look for your Sass
sass:
  sass_dir: _sass
  style: compressed

# Build settings
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap